### ISSUE TITLE
ValueError: No gradients provided for any variable

### ISSUE THREAD

**Issue by leiup** [andrewliao11/CoGAN-tensorflow#4] opened 2017-09-11 08:14 UTC
When running the training codes, there exists one problem: "ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients". How to solve it? Thanks.

**Comment by andrewliao11** [comment] 2017-09-11 15:11
what's your tf version? Using tf.0.12 should be fine

**Comment by leiup** [comment] 2017-09-12 03:09
I use tf 1.0. How to update the source codes? Thank you very much!

**Comment by andrewliao11** [comment] 2017-09-12 16:02
Hi @leihe001 , in fact, I can't reproduce the error you encountered.
On the other hand, I just change the requirement to tf.0.12. I'll first close this issue and you can reopen it when you fail in tf.0.12 environment.

**Closed as completed by andrewliao11** 2017-09-12 16:02 UTC

**Comment by leiup** [comment] 2017-09-13 00:43
OK， thank you all the same!
